IF OBJECT_ID('dbo.SP_GetThongTinGiaoVienTuMa', 'P') IS NOT NULL
    DROP PROCEDURE dbo.SP_GetThongTinGiaoVienTuMa;
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_GetThongTinGiaoVienTuMa] @MAGV NCHAR (8)
AS
BEGIN
	SELECT MAGV, HO, TEN, HOCVI, MAKH
	FROM dbo.GiaoVien 
	   WHERE MAGV = @MAGV
END;
GO