IF OBJECT_ID('dbo.SP_GetMonHocTuMaMH', 'P') IS NOT NULL
    DROP PROCEDURE dbo.SP_GetMonHocTuMaMH;
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_GetMonHocTuMaMH] @MAMH NCHAR (5)
AS
BEGIN
	SELECT MAMH, TENMH
	FROM dbo.MonHoc
	WHERE MAMH = @MAMH
END;
GO