IF OBJECT_ID('dbo.SP_GetGiaoVienDangKy', 'P') IS NOT NULL
    DROP PROCEDURE dbo.SP_GetGiaoVienDangKy;
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_GetGiaoVienDangKy]
@MALOP NCHAR (8), @MAMH NCHAR (5), @LAN smallint
AS
BEGIN
	SELECT *
	FROM dbo.GiaoVien_DangKy
	WHERE MALOP = @MALOP AND MAMH = @MAMH AND LAN = @LAN
END;
GO
