USE [THITN]
GO

IF OBJECT_ID('SP_InsertListBoDe', 'P') IS NOT NULL
    DROP PROC SP_InsertListBoDe
GO

-- 1. SP THÊM CÂU HỎI
CREATE PROCEDURE [dbo].[SP_InsertListBoDe]
    @MAMH NCHAR(5), 
    @TRINHDO NCHAR(1), 
    @NOIDUNG NTEXT, 
    @A NTEXT, 
    @B NTEXT, 
    @C NTEXT = NULL, 
    @D NTEXT = NULL, 
    @DAPAN NCHAR(1), 
    @MAGV NCHAR(8)
AS
BEGIN
    INSERT INTO BODE (MAMH, TRINHDO, NOIDUNG, A, B, C, D, DAPAN, MAGV) 
    VALUES (@MAMH, @TRINHDO, @NOIDUNG, @A, @B, @C, @D, @DAPAN, @MAGV)
END
GO

-- 2. SP CẬP NHẬT CÂU HỎI
CREATE PROCEDURE [dbo].[SP_UPDATE_BODE]
    @CAUHOI INT,
    @MAMH NCHAR(5), 
    @TRINHDO NCHAR(1), 
    @NOIDUNG NTEXT, 
    @A NTEXT, 
    @B NTEXT, 
    @C NTEXT = NULL, 
    @D NTEXT = NULL, 
    @DAPAN NCHAR(1), 
    @MAGV NCHAR(8)
AS
BEGIN
    UPDATE BODE 
    SET MAMH = @MAMH, TRINHDO = @TRINHDO, NOIDUNG = @NOIDUNG, 
        A = @A, B = @B, C = @C, D = @D, DAPAN = @DAPAN
    WHERE CAUHOI = @CAUHOI AND MAGV = @MAGV
END
GO

-- 3. SP XÓA CÂU HỎI
CREATE PROCEDURE [dbo].[SP_DELETE_BODE]
    @CAUHOI INT,
    @MAGV NCHAR(8)
AS
BEGIN
    DELETE FROM BODE WHERE CAUHOI = @CAUHOI AND MAGV = @MAGV
END
GO