USE [THITN]
GO

IF OBJECT_ID('dbo.SP_InsertGiaoVienDangKy', 'P') IS NOT NULL
    DROP PROCEDURE dbo.SP_InsertGiaoVienDangKy;
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- Thêm mới một lịch đăng ký thi
CREATE PROCEDURE [dbo].[SP_InsertGiaoVienDangKy]
    @MAGV NCHAR(8),
    @MALOP NCHAR(8),
    @MAMH NCHAR(5),
    @TRINHDO NCHAR(1),
    @NGAYTHI DATETIME,
    @LAN SMALLINT,
    @SOCAUTHI SMALLINT,
    @THOIGIAN SMALLINT
AS
BEGIN
    SET NOCOUNT ON;
    
    INSERT INTO GiaoVien_DangKy 
        (MAGV, MALOP, MAMH, TRINHDO, NGAYTHI, LAN, SOCAUTHI, THOIGIAN)
    VALUES 
        (@MAGV, @MALOP, @MAMH, @TRINHDO, @NGAYTHI, @LAN, @SOCAUTHI, @THOIGIAN);
END
GO